stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - raspberry
  only:
    - ux-app
  script:
    - echo "Début du déploiement sur le Raspberry Pi..."
    - cd $CI_PROJECT_DIR
    - docker compose down --remove-orphans
    - docker compose up --build -d
    - echo "Déploiement terminé - App disponible sur http://localhost:8080"
