services:
  color-room:
    build:
      context: ./app
    container_name: color-room
    ports:
      - "8080:3000"
    environment:
      - COLOR_ROOM_PORT=3000
      - COLOR_ROOM_DB_PATH=/data/ColorRoomDB.db
    volumes:
      - ../SupervisionAPI/data/ColorRoomDB.db:/data/ColorRoomDB.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock  # Permet Ã  Portainer de piloter Docker
      - portainer_data:/data                       # Persistance des rÃ©glages Portainer
    ports:
      - "9000:9000"  # Interface HTTP (optionnel)
      - "9443:9443"  # Interface HTTPS (recommandÃ©)

volumes:
  portainer_data:
