@startuml ColorRoom_Seq_CS160
skinparam sequenceArrowColor #2563EB
skinparam sequenceParticipantBackgroundColor #EFF6FF
skinparam sequenceParticipantBorderColor #2563EB

title ColorRoom - Mesure CS-160

actor Joueur
participant "App" as APP
participant "API /cs160" as API
participant "CS-160" as CS

Joueur -> APP : lance la mesure
APP -> API : POST measure
API -> CS : connect + lecture
CS --> API : x, y, Lv
API --> APP : résultat
APP --> Joueur : couleur + score

@enduml
