@startuml ColorRoom_Seq_Jeu
skinparam sequenceArrowColor #2563EB
skinparam sequenceParticipantBackgroundColor #EFF6FF
skinparam sequenceParticipantBorderColor #2563EB

title ColorRoom - Exécution d'un jeu

actor Joueur
participant "Runtime" as RT
participant "API /supervision" as API
participant "Dalles" as LED

Joueur -> RT : Jouer
RT -> RT : parcours du graphe (noeuds)
loop chaque noeud couleur
  RT -> API : envoi couleurs
  API -> LED : allume
end
RT --> Joueur : score final

@enduml
