@startuml ColorRoom_Seq_MP
skinparam sequenceArrowColor #DC2626
skinparam sequenceParticipantBackgroundColor #FFF1F2
skinparam sequenceParticipantBorderColor #DC2626

title ColorRoom - Session multijoueur

actor "Hôte" as H
actor "Joueur" as J
participant "API /mp" as API
database "SQLite" as DB

H -> API : crée session
API -> DB : code partie
API --> H : code (ex: XKQF)
J -> API : rejoint (code)
API -> DB : ajoute joueur
H -> API : démarre
J -> API : envoie son coup
API -> DB : maj état
H -> API : lit l'état
H --> H : met à jour les dalles

@enduml
